export const APPOINTMENT_BY_DATE_SUCCESS = 'APPOINTMENT_BY_DATE_SUCCESS';
export const APPOINTMENT_BY_DATE_REQUEST = 'APPOINTMENT_BY_DATE_REQUEST';
export const APPOINTMENT_BY_DATE_FAILURE = 'APPOINTMENT_BY_DATE_FAILURE';
